service: stock-crawler
package:
  include:
    - python_libs/**
provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  architecture: x86_64
  deploymentBucket:
    name: fiflowbucket
  environment:
    DYNAMODB_TABLE: fiflow-users
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
functions:
  mainCrawler:
    handler: lambda_main.main
    timeout: 180
    memorySize: 256
  indexCrawler:
    handler: index_crawler.main
    timeout: 180
    memorySize: 256
  stockInfoCrawler:
    handler: get_stock_info.main
    timeout: 180
    memorySize: 256
  getRealtimePrice:
    handler: get_realtime_price.main
    timeout: 28
    memorySize: 128
    events:
      - http:
          path: realtime-price
          method: get
          cors: true