# api-server/serverless.yml
service: api-server
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  memorySize: 256
  environment:
    DYNAMODB_TABLE: fiflow-users
    JWT_SECRET: ${env:JWT_SECRET}
    KAKAO_CLIENT_ID: ${env:KAKAO_CLIENT_ID}
    KAKAO_CLIENT_SECRET: ${env:KAKAO_CLIENT_SECRET}
    KAKAO_REDIRECT_URI: ${env:KAKAO_REDIRECT_URI}
    CORS_ORIGIN: ${env:CORS_ORIGIN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:TagResource
          Resource: arn:aws:logs:ap-northeast-2:443370694043:log-group:/aws/lambda/api-server-dev*:*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:ap-northeast-2:443370694043:table/fiflow-users
            - arn:aws:dynamodb:ap-northeast-2:443370694043:table/fiflow-users/index/*
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:ap-northeast-2:443370694043:function:stock-crawler-dev-mainCrawler

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'node_modules/**'

plugins:

functions:
  app:
    handler: app.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: ANY